import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, Bell, Boxes, ChevronDown, CircleHelp, LayoutDashboard, Menu, MoreHorizontal, Plus, ReceiptText, RotateCcw, Settings, ShoppingCart, Store, Users, Wallet, X } from 'lucide-react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { initialState, formatINR, getProductStatus, roleDetails } from './data/demoData'
import type { AppState, Role } from './data/demoData'
import { ActivityView, DailyView, InventoryView, MonthlyView } from './Views'
import type { Product } from './data/demoData'
import { RoleHomeView, RoleManagementView } from './RoleViews'
import { CorrectionModal, ExpenseModal, ProductDetailModal, PurchaseModal } from './TransactionModals'
import { NotificationsPanel, seedNotifications } from './NotificationsPanel'
import type { NotificationItem } from './NotificationsPanel'
import { LoginView } from './LoginView'
import './index.css'

type NavItem = { label: string; icon: typeof LayoutDashboard }
const navItems: NavItem[] = [{ label: 'Home', icon: LayoutDashboard }, { label: 'Daily', icon: ReceiptText }, { label: 'Monthly', icon: Wallet }, { label: 'Inventory', icon: Boxes }, { label: 'Activity log', icon: RotateCcw }]
const managerNavItems: NavItem[] = [{ label: 'Shops', icon: Store }, { label: 'Managers', icon: Users }, { label: 'Shareholders', icon: Users }, { label: 'Incentives', icon: ArrowUpRight }]
const shareholderNavItems: NavItem[] = [{ label: 'Reports', icon: ReceiptText }]
const chartData = [{ day: '10 Jun', sales: 6200, expenses: 1800 }, { day: '11 Jun', sales: 7900, expenses: 2200 }, { day: '12 Jun', sales: 6800, expenses: 1600 }, { day: '13 Jun', sales: 9200, expenses: 3100 }, { day: '14 Jun', sales: 8400, expenses: 2500 }, { day: '15 Jun', sales: 12840, expenses: 3420 }]
const roleOptions: Role[] = ['manager', 'super-manager', 'shareholder']

function App() {
  const [role, setRole] = useState<Role>('manager')
  const [state, setState] = useState<AppState>(() => { const saved = localStorage.getItem('shopflow-demo-state'); return saved ? JSON.parse(saved) : initialState })
  const [activeNav, setActiveNav] = useState('Home')
  const [showRoleMenu, setShowRoleMenu] = useState(false)
  const [showSale, setShowSale] = useState(false)
  const [showExpense, setShowExpense] = useState(false)
  const [showPurchase, setShowPurchase] = useState(false)
  const [correctionProduct, setCorrectionProduct] = useState<Product | null>(null)
  const [detailProduct, setDetailProduct] = useState<Product | null>(null)
  const [toast, setToast] = useState('')
  const [showNotifications, setShowNotifications] = useState(false)
  const [showLogin, setShowLogin] = useState(false)
  const [showMobileMenu, setShowMobileMenu] = useState(false)
  const [notifications, setNotifications] = useState<NotificationItem[]>(() => { const saved = localStorage.getItem('shopflow-demo-notifications'); return saved ? JSON.parse(saved) : seedNotifications })
  useEffect(() => localStorage.setItem('shopflow-demo-state', JSON.stringify(state)), [state])
  useEffect(() => localStorage.setItem('shopflow-demo-notifications', JSON.stringify(notifications)), [notifications])
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 3200); return () => window.clearTimeout(timer) }, [toast])
  const details = roleDetails[role]
  const lowStock = state.products.filter((product) => getProductStatus(product) !== 'Healthy')
  const isViewer = role === 'shareholder'
  const resetDemo = () => { setState(initialState); setNotifications(seedNotifications); setToast('Demo data restored') }
  const unreadNotifications = notifications.filter((item) => item.unread).length
  const recordSale = (amount: number, productId: string, quantity: number) => { setState((current) => ({ ...current, balance: current.balance + amount, sales: current.sales + amount, products: current.products.map((product) => product.id === productId ? { ...product, stock: Math.max(0, product.stock - quantity) } : product), transactions: [{ id: crypto.randomUUID(), type: 'Sale', title: 'Counter sale', amount, time: 'Just now', detail: 'Demo transaction · UPI' }, ...current.transactions] })); setShowSale(false); setToast('Sale recorded and inventory updated') }
  const recordExpense = (amount: number, category: string) => { setState((current) => ({ ...current, balance: current.balance - amount, expenses: current.expenses + amount, transactions: [{ id: crypto.randomUUID(), type: 'Expense', title: category, amount, time: 'Just now', detail: 'Demo expense' }, ...current.transactions] })); setShowExpense(false); setToast('Expense recorded and balance updated') }
  const recordPurchase = (amount: number, productId: string, quantity: number, supplier: string) => { setState((current) => ({ ...current, balance: current.balance - amount, purchases: current.purchases + amount, products: current.products.map((product) => product.id === productId ? { ...product, stock: product.stock + quantity } : product), transactions: [{ id: crypto.randomUUID(), type: 'Purchase', title: supplier, amount, time: 'Just now', detail: 'Stock replenishment' }, ...current.transactions] })); setShowPurchase(false); setToast('Purchase recorded and inventory updated') }
  const recordCorrection = (newStock: number, reason: string) => { if (!correctionProduct) return; const difference = newStock - correctionProduct.stock; setState((current) => ({ ...current, products: current.products.map((product) => product.id === correctionProduct.id ? { ...product, stock: newStock } : product), transactions: [{ id: crypto.randomUUID(), type: 'Stock Correction', title: correctionProduct.name, amount: Math.abs(difference), time: 'Just now', detail: reason }, ...current.transactions] })); setCorrectionProduct(null); setToast('Stock corrected and activity recorded') }
  const initials = details.name.split(' ').map((part) => part[0]).join('')
  if (showLogin) return <LoginView onLogin={(nextRole) => { setRole(nextRole); setShowLogin(false); setActiveNav('Home'); setToast(`Signed in as ${roleDetails[nextRole].label}`) }} />
  return <div className="app-shell">
    <aside className={showMobileMenu ? 'sidebar mobile-open' : 'sidebar'}><div className="brand"><div className="brand-mark"><Store size={19} /></div><span>shop<span>flow</span></span><button className="icon-button drawer-close" aria-label="Close menu" onClick={() => setShowMobileMenu(false)}><X size={18} /></button></div><div className="shop-switcher"><div className="shop-avatar">MS</div><div><strong>Main Street Shop</strong><small>MG Road, Bengaluru</small></div><ChevronDown size={16} /></div><nav className="side-nav" aria-label="Main navigation"><p className="nav-caption">Workspace</p>{navItems.map((item) => <button className={activeNav === item.label ? 'nav-item active' : 'nav-item'} key={item.label} onClick={() => { setActiveNav(item.label); setShowMobileMenu(false) }}><item.icon size={18} /><span>{item.label}</span>{item.label === 'Inventory' && lowStock.length > 0 && <em>{lowStock.length}</em>}</button>)}{role === 'super-manager' && <><p className="nav-caption">Business</p>{managerNavItems.map((item) => <button className={activeNav === item.label ? 'nav-item active' : 'nav-item'} key={item.label} onClick={() => { setActiveNav(item.label); setShowMobileMenu(false) }}><item.icon size={18} /><span>{item.label}</span></button>)}</>}{role === 'shareholder' && <><p className="nav-caption">Reports</p>{shareholderNavItems.map((item) => <button className={activeNav === item.label ? 'nav-item active' : 'nav-item'} key={item.label} onClick={() => { setActiveNav(item.label); setShowMobileMenu(false) }}><item.icon size={18} /><span>{item.label}</span></button>)}</>}{!isViewer && <><p className="nav-caption">Manage</p><button className="nav-item" onClick={() => { setShowSale(true); setShowMobileMenu(false) }}><Plus size={18} /><span>New transaction</span></button></>}</nav><div className="sidebar-footer"><button className="nav-item"><Settings size={18} /><span>Settings</span></button><button className="nav-item"><CircleHelp size={18} /><span>Help centre</span></button><div className="sidebar-user"><div className="user-avatar">{initials}</div><div><strong>{details.name}</strong><small>{details.label}</small></div><MoreHorizontal size={18} /></div></div></aside>{showMobileMenu && <button className="drawer-backdrop" aria-label="Close menu" onClick={() => setShowMobileMenu(false)} />}
    <main className="main-content"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Open menu" onClick={() => setShowMobileMenu(true)}><Menu size={20} /></button><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>{activeNav}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications" onClick={() => setShowNotifications(!showNotifications)}><Bell size={19} />{unreadNotifications > 0 && <i />}</button>{showNotifications && <NotificationsPanel items={notifications} onClose={() => setShowNotifications(false)} onRead={(id) => setNotifications((current) => current.map((item) => item.id === id ? { ...item, unread: false } : item))} onReadAll={() => setNotifications((current) => current.map((item) => ({ ...item, unread: false })))} />}<div className="role-control"><button className="role-button" onClick={() => setShowRoleMenu(!showRoleMenu)}><div className="user-avatar small">{initials}</div><span>{details.label}</span><ChevronDown size={15} /></button>{showRoleMenu && <div className="role-menu">{roleOptions.map((option) => <button key={option} onClick={() => { setRole(option); setShowRoleMenu(false) }}>{roleDetails[option].label}<small>{roleDetails[option].email}</small></button>)}<hr /><button onClick={() => { setShowRoleMenu(false); setShowLogin(true) }}>Open demo login</button><button onClick={resetDemo}><RotateCcw size={14} /> Reset demo data</button></div>}</div></div></header>
      <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">Sunday, 15 June 2024 <span className="live-dot" /> Live demo</div><h1>{role === 'shareholder' ? 'Business overview' : role === 'super-manager' ? 'Business command centre' : 'Good morning, Arun'}</h1><p>{role === 'shareholder' ? 'A clear view of your investment performance.' : role === 'super-manager' ? 'A complete view across every shop in your network.' : 'Here is what is happening at Main Street Shop today.'}</p></div><button className="date-button">15 Jun 2024 <ChevronDown size={15} /></button></div>
        {activeNav === 'Daily' ? <DailyView state={state} /> : activeNav === 'Monthly' ? <MonthlyView state={state} /> : activeNav === 'Inventory' ? <InventoryView state={state} onCorrect={setCorrectionProduct} onSelect={setDetailProduct} /> : activeNav === 'Activity log' ? <ActivityView state={state} /> : ['Shops', 'Managers', 'Shareholders', 'Incentives', 'Reports'].includes(activeNav) ? <RoleManagementView role={role} state={state} section={activeNav} /> : role !== 'manager' ? <RoleHomeView role={role} state={state} /> : <>
        <section className="hero-metrics"><div className="balance-panel"><div className="metric-label">Available balance <span className="info-dot">i</span></div><div className="balance-value">{formatINR(state.balance)}</div><div className="balance-change"><ArrowUpRight size={15} /> 12.8% <span>vs last month</span></div><div className="balance-spark"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="balanceGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b9d4ff" stopOpacity={0.5} /><stop offset="100%" stopColor="#b9d4ff" stopOpacity={0} /></linearGradient></defs><Area type="monotone" dataKey="sales" stroke="#2563eb" strokeWidth={2} fill="url(#balanceGradient)" /></AreaChart></ResponsiveContainer></div></div><MetricCard label="Today's sales" value={formatINR(state.sales)} change="8.4%" positive icon={<ArrowUpRight size={17} />} /><MetricCard label="Today's expenses" value={formatINR(state.expenses)} change="3.2%" positive={false} icon={<ArrowDownRight size={17} />} /></section>
        <section className="dashboard-grid"><div className="panel trend-panel"><div className="panel-heading"><div><h2>Sales overview</h2><p>Revenue performance over the last 6 days</p></div><button className="select-button">This week <ChevronDown size={14} /></button></div><div className="chart-legend"><span><b className="legend-sales" /> Sales</span><span><b className="legend-expenses" /> Expenses</span></div><div className="main-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ top: 12, right: 6, bottom: 0, left: -20 }}><defs><linearGradient id="salesGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={0.18} /><stop offset="100%" stopColor="#2563eb" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 11 }} tickFormatter={(value) => `${value / 1000}k`} /><Tooltip formatter={(value) => formatINR(Number(value))} /><Area type="monotone" dataKey="sales" stroke="#2563eb" strokeWidth={2.5} fill="url(#salesGradient)" /><Area type="monotone" dataKey="expenses" stroke="#f59e0b" strokeWidth={2} fill="none" /></AreaChart></ResponsiveContainer></div></div><div className="panel quick-panel"><div className="panel-heading"><div><h2>Quick actions</h2><p>Keep your shop moving</p></div></div><div className="quick-actions"><ActionButton icon={<ShoppingCart size={19} />} label="Add sale" onClick={() => !isViewer && setShowSale(true)} disabled={isViewer} /><ActionButton icon={<ReceiptText size={19} />} label="Add expense" onClick={() => !isViewer && setShowExpense(true)} disabled={isViewer} /><ActionButton icon={<Boxes size={19} />} label="Add purchase" onClick={() => !isViewer && setShowPurchase(true)} disabled={isViewer} /></div><div className="balance-note"><span className="note-icon"><Wallet size={16} /></span><div><strong>Balance is healthy</strong><p>Up {formatINR(5480)} this week</p></div><ArrowUpRight size={16} /></div></div></section>
        <section className="lower-grid"><div className="panel activity-panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>The latest movement in your shop</p></div><button className="text-button" onClick={() => setActiveNav('Activity log')}>View all <ArrowUpRight size={15} /></button></div><div className="transaction-list">{state.transactions.slice(0, 4).map((transaction) => <TransactionRow key={transaction.id} transaction={transaction} />)}</div></div><div className="panel stock-panel"><div className="panel-heading"><div><h2>Needs attention</h2><p>Stock levels to review</p></div><button className="text-button" onClick={() => setActiveNav('Inventory')}>Inventory <ArrowUpRight size={15} /></button></div>{lowStock.length === 0 ? <div className="empty-state">All products are well stocked.</div> : <div className="stock-list">{lowStock.slice(0, 3).map((product) => <div className="stock-row" key={product.id}><div className="product-icon">{product.name.slice(0, 1)}</div><div className="stock-product"><strong>{product.name}</strong><small>Min. {product.minimumStock} units</small></div><span className={product.stock === 0 ? 'status danger' : 'status warning'}>{product.stock === 0 ? 'Out of stock' : `${product.stock} left`}</span></div>)}</div>}</div></section></>}</div></main>
    <nav className="mobile-nav">{navItems.map((item) => <button className={activeNav === item.label ? 'active' : ''} key={item.label} onClick={() => setActiveNav(item.label)}><item.icon size={19} /><span>{item.label === 'Activity log' ? 'Log' : item.label}</span></button>)}</nav>{showSale && <SaleModal products={state.products} onClose={() => setShowSale(false)} onSave={recordSale} />}{showExpense && <ExpenseModal onClose={() => setShowExpense(false)} onSave={recordExpense} />}{showPurchase && <PurchaseModal products={state.products} onClose={() => setShowPurchase(false)} onSave={recordPurchase} />}{detailProduct && <ProductDetailModal product={detailProduct} onClose={() => setDetailProduct(null)} onCorrect={() => { setCorrectionProduct(detailProduct); setDetailProduct(null) }} />}{correctionProduct && <CorrectionModal product={correctionProduct} onClose={() => setCorrectionProduct(null)} onSave={recordCorrection} />}{toast && <div className="toast"><div className="toast-check">✓</div>{toast}<button onClick={() => setToast('')} aria-label="Dismiss"><X size={15} /></button></div>}
  </div>
}

function MetricCard({ label, value, change, positive, icon }: { label: string; value: string; change: string; positive: boolean; icon: React.ReactNode }) { return <div className="metric-card"><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className={positive ? 'metric-change positive' : 'metric-change negative'}>{icon}{change} <span>vs yesterday</span></div></div> }
function ActionButton({ icon, label, onClick, disabled }: { icon: React.ReactNode; label: string; onClick: () => void; disabled?: boolean }) { return <button className="action-button" onClick={onClick} disabled={disabled}><span>{icon}</span>{label}<Plus size={15} /></button> }
function TransactionRow({ transaction }: { transaction: AppState['transactions'][number] }) { const colors = { Sale: 'blue', Purchase: 'orange', Expense: 'red', 'Stock Correction': 'purple' }; return <div className={`transaction-row`}><div className={`transaction-icon ${colors[transaction.type]}`}><ArrowUpRight size={16} /></div><div className="transaction-copy"><strong>{transaction.title}</strong><small>{transaction.type} · {transaction.detail}</small></div><div className="transaction-amount"><strong className={transaction.type === 'Sale' ? 'income' : ''}>{transaction.type === 'Sale' ? '+' : '-'}{formatINR(transaction.amount)}</strong><small>{transaction.time}</small></div></div> }
function SaleModal({ products, onClose, onSave }: { products: AppState['products']; onClose: () => void; onSave: (amount: number, productId: string, quantity: number) => void }) { const [productId, setProductId] = useState(products[0].id); const [quantity, setQuantity] = useState(1); const product = products.find((item) => item.id === productId) ?? products[0]; const total = product.sellingPrice * quantity; return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={(event) => event.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">New transaction</span><h2>Record a sale</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={18} /></button></div><label>Product<select value={productId} onChange={(event) => setProductId(event.target.value)}>{products.map((item) => <option key={item.id} value={item.id}>{item.name} · {formatINR(item.sellingPrice)}</option>)}</select></label><label>Quantity<div className="quantity-control"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}>-</button><strong>{quantity}</strong><button onClick={() => setQuantity(quantity + 1)}>+</button></div></label><div className="sale-total"><span>Total sale</span><strong>{formatINR(total)}</strong></div><button className="primary-button" onClick={() => onSave(total, product.id, quantity)}>Save sale <ArrowUpRight size={16} /></button></div></div> }

export default App
