import { useState } from 'react'
import { ArrowDownRight, ArrowUpRight, Search } from 'lucide-react'
import { formatINR, getProductStatus } from './data/demoData'
import type { AppState, Product } from './data/demoData'

export function MonthlyView({ state }: { state: AppState }) {
  const balanceBeforeExpense = state.balance + 1850
  const otherEarnings = 3200
  return <div className="workspace-view"><ViewIntro eyebrow="June 2024 · Monthly review" title="Monthly overview" copy="Understand the movement behind this month's balance." /><div className="view-metrics"><ViewMetric label="Total sales" value={formatINR(state.sales * 6)} tone="green" /><ViewMetric label="Total expenses" value={formatINR(state.expenses * 6)} tone="orange" /><ViewMetric label="Total purchases" value={formatINR(state.purchases * 4)} tone="red" /><ViewMetric label="Current balance" value={formatINR(state.balance)} tone="blue" /></div><div className="monthly-grid"><div className="panel"><div className="panel-heading"><div><h2>Balance movement</h2><p>Before and after monthly adjustments</p></div><button className="select-button">June 2024 <span>⌄</span></button></div><div className="balance-breakdown"><BreakdownRow label="Balance before monthly expense" value={balanceBeforeExpense} /><BreakdownRow label="Monthly expenses" value={-1850} negative /><BreakdownRow label="Other earnings" value={otherEarnings} /><div className="breakdown-total"><span>Balance after monthly expense</span><strong>{formatINR(state.balance + otherEarnings)}</strong></div></div></div><div className="panel"><div className="panel-heading"><div><h2>Daily earnings</h2><p>Average movement by day</p></div></div><div className="earnings-bars"><div><span style={{ height: '46%' }} /><small>10</small></div><div><span style={{ height: '66%' }} /><small>11</small></div><div><span style={{ height: '54%' }} /><small>12</small></div><div><span style={{ height: '78%' }} /><small>13</small></div><div><span style={{ height: '71%' }} /><small>14</small></div><div><span style={{ height: '92%' }} /><small>15</small></div></div><div className="earnings-legend"><span><b /> Daily sales</span><strong>{formatINR(otherEarnings)} other earnings</strong></div></div></div></div>
}

export function DailyView({ state }: { state: AppState }) {
  const net = state.sales - state.expenses - state.purchases
  return <div className="workspace-view"><ViewIntro eyebrow="Sunday, 15 June 2024" title="Daily operations" copy="Keep today's movement clear and controlled." /><div className="view-metrics"><ViewMetric label="Sales" value={formatINR(state.sales)} tone="green" /><ViewMetric label="Expenses" value={formatINR(state.expenses)} tone="orange" /><ViewMetric label="Purchases" value={formatINR(state.purchases)} tone="red" /><ViewMetric label="Net movement" value={`${net >= 0 ? '+' : ''}${formatINR(net)}`} tone="blue" /></div><div className="panel table-panel"><div className="panel-heading"><div><h2>Today's timeline</h2><p>Every recorded movement for Main Street Shop</p></div><button className="select-button">15 Jun 2024</button></div><div className="timeline">{state.transactions.map((transaction) => <div className="timeline-row" key={transaction.id}><span className={`timeline-dot ${transaction.type.toLowerCase().replace(' ', '-')}`} /><div className="timeline-time">{transaction.time}</div><div className="timeline-main"><strong>{transaction.title}</strong><small>{transaction.type} · {transaction.detail}</small></div><strong className={transaction.type === 'Sale' ? 'income' : ''}>{transaction.type === 'Sale' ? '+' : '-'}{formatINR(transaction.amount)}</strong></div>)}</div></div></div>
}

export function InventoryView({ state, onCorrect, onSelect }: { state: AppState; onCorrect: (product: Product) => void; onSelect: (product: Product) => void }) {
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('All')
  const products = state.products.filter((product) => product.name.toLowerCase().includes(query.toLowerCase()) && (filter === 'All' || getProductStatus(product) === filter))
  const lowStock = state.products.filter((product) => getProductStatus(product) === 'Low stock').length
  const outOfStock = state.products.filter((product) => getProductStatus(product) === 'Out of stock').length
  const value = state.products.reduce((total, product) => total + product.stock * product.purchasePrice, 0)
  return <div className="workspace-view"><ViewIntro eyebrow="Stock control" title="Inventory" copy="Know what is moving, what is low, and what needs attention." /><div className="view-metrics"><ViewMetric label="Total products" value={String(state.products.length)} tone="blue" /><ViewMetric label="Low stock" value={String(lowStock)} tone="orange" /><ViewMetric label="Out of stock" value={String(outOfStock)} tone="red" /><ViewMetric label="Inventory value" value={formatINR(value)} tone="green" /></div><div className="panel table-panel"><div className="inventory-toolbar"><div className="search-box"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products" aria-label="Search products" /></div><div className="filter-group">{['All', 'Healthy', 'Low stock', 'Out of stock'].map((option) => <button className={filter === option ? 'filter-active' : ''} key={option} onClick={() => setFilter(option)}>{option}</button>)}</div></div><div className="product-table"><div className="product-table-head"><span>Product</span><span>Category</span><span>Stock</span><span>Price</span><span>Status</span><span>Action</span></div>{products.length === 0 ? <div className="empty-state">No products match your search.</div> : products.map((product) => <ProductRow product={product} key={product.id} onCorrect={onCorrect} onSelect={onSelect} />)}</div></div></div>
}

export function ActivityView({ state }: { state: AppState }) { const [filter, setFilter] = useState('All'); const filters = ['All', 'Sales', 'Purchases', 'Expenses', 'Inventory']; const filtered = state.transactions.filter((transaction) => filter === 'All' || (filter === 'Sales' && transaction.type === 'Sale') || (filter === 'Purchases' && transaction.type === 'Purchase') || (filter === 'Expenses' && transaction.type === 'Expense') || (filter === 'Inventory' && transaction.type === 'Stock Correction')); return <div className="workspace-view"><ViewIntro eyebrow="Audit trail" title="Activity log" copy="A transparent record of everything that changed." /><div className="panel table-panel"><div className="panel-heading"><div><h2>Recent events</h2><p>Recorded actions in chronological order</p></div><div className="filter-group">{filters.map((item) => <button className={filter === item ? 'filter-active' : ''} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="activity-table">{filtered.length === 0 ? <div className="empty-state">No activity in this category yet.</div> : filtered.map((transaction) => <div className="activity-row" key={transaction.id}><div className={`transaction-icon ${transaction.type === 'Sale' ? 'blue' : transaction.type === 'Expense' ? 'red' : 'orange'}`}><ArrowUpRight size={16} /></div><div><strong>{transaction.type} recorded</strong><small>{transaction.title} · Arun Mehta</small></div><span>{formatINR(transaction.amount)}</span><time>{transaction.time}</time></div>)}</div></div></div> }

function ProductRow({ product, onCorrect, onSelect }: { product: Product; onCorrect: (product: Product) => void; onSelect: (product: Product) => void }) { const status = getProductStatus(product); return <div className="product-table-row"><button className="product-name-cell product-link" onClick={() => onSelect(product)}><div className="product-icon">{product.name.slice(0, 1)}</div><div><strong>{product.name}</strong><small>{product.sku}</small></div></button><span>{product.category}</span><strong>{product.stock} units</strong><span>{formatINR(product.sellingPrice)}</span><span className={`status ${status === 'Healthy' ? 'healthy' : status === 'Low stock' ? 'warning' : 'danger'}`}>{status}</span><button className="row-action" onClick={() => onCorrect(product)}>Correct</button></div> }
function BreakdownRow({ label, value, negative }: { label: string; value: number; negative?: boolean }) { return <div className="breakdown-row"><span>{label}</span><strong className={negative ? 'negative' : 'income'}>{negative ? '-' : '+'}{formatINR(Math.abs(value))}</strong></div> }
export function ViewIntro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="view-intro"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{copy}</p></div></div> }
function ViewMetric({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className={`view-metric ${tone}`}><span>{label}</span><strong>{value}</strong>{tone === 'green' ? <ArrowUpRight size={16} /> : tone === 'red' ? <ArrowDownRight size={16} /> : null}</div> }
